---
# tasks file for roles/suma

- name: Get LPAR processor
  ansible.builtin.script: 'suma.sh {{item.LPARNAME}}' 
  register: resultado
  loop: '{{ lpar_servers }}'

- name: Clean var
  set_fact:
    lpar_proc: '{{lpar_proc | default(0) | float + item.stdout_lines[0] | float }}'
  with_items:
    - '{{ resultado.results}}'
  no_log: false
 
- name: Debug Suma
  debug:
    msg: '{{lpar_proc}}'


    