---
# tasks file for roles/lpar


- name: Include credentials for connecting to the HMC
  include_vars:
    file: credentials.yml

- name: Shutting down LPARs
  ansible.builtin.script: 'shutdownLPAR.sh {{item.LPARNAME}} {{hmc_user}} {{hmc_hostname}} {{item.PRI_SYS}}' 
  register: resultado
  loop: '{{ lpar_servers }}'

- name: Clean loop output
  set_fact:
    clean_out: '{{ clean_out|default([]) + [item.stdout] }}'
  with_items:
    - '{{ resultado.results }}'
  no_log: True

- name: Debug Messages
  debug:
    msg: '{{clean_out}}'

  