---
# tasks file for roles/sgm

- name: Suspend Global Mirror
  ansible.builtin.script: 'suspendGM.sh {{item.LPARNAME}}' 
  register: resultado
  #until: resultado.stdout!='ok'
  #retries: 30
  #delay: 25
  loop: '{{ lpar_servers }}'


- name: Debug Messages
  debug:
    msg: '{{resultado}}'

- name: Clean loop output
  set_fact:
    clean_out: '{{ clean_out|default([]) + [item.stdout_lines[0]] }}'
  with_items:
    - '{{ resultado.results }}'
  no_log: True
  #failed_when: item.stdout_lines[0]=='nook'

- name: Debug Messages
  debug:
    msg: '{{clean_out}}'