
- name: Suspend Global Mirror {{item.lpar.name}}
  ansible.builtin.script: 'suspendGM.sh {{item.lpar.name}}'
  register: resultado
  until: resultado.stdout_lines[0]=='ok'
  retries: 30
  delay: 25


- name: Debug Messages
  debug:
    msg: '{{resultado}}'

