---
# tasks file for roles/mtdca

- name: Include credentials for connecting to the HMC
  include_vars:
    file: credentials.yml

- name: Execute Metro Mirror
  include_tasks: metro.yml
  loop: '{{ lpar_servers }}'
  loop_control:
    loop_var: item
  when:  session_type=='MM'


- name: Execute Global Mirror
  include_tasks: global.yml
  when:  session_type=='GM'



    