
- name: Suspend Metro Mirror {{item.LPARNAME}}
  ansible.builtin.script: 'suspendGM.sh {{item.LPARNAME}}'
  register: resultado
  failed_when: resultado.stdout_lines[0]=='ok'


- name: Debug Messages
  debug:
    msg: '{{resultado}}'

