
- name: Suspend Metro Mirror {{item.LPARNAME}}
  ansible.builtin.script: 'suspendGM.sh {{item.LPARNAME}}'
  register: resultado
  #until: resultado.stdout_lines[1]=='ok'
  #retries: 5
  #delay: 5


- name: Debug Messages
  debug:
    msg: '{{resultado}}'

